package com.example.handlers;

import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;

import com.example.Property;
import com.example.utils.PropertyAdjacencyUtils;

/**
 * DetailsButtonHandler handles the action when the "Details" button is clicked.
 * This class is responsible for showing the details of the selected property.
 */
public class DetailsButtonHandler implements ActionListener {

    private JPanel panel;
    private List<Property> properties;

    /**
     * Constructor for DetailsButtonHandler.
     *
     * @param panel The panel that contains the button.
     * @param properties The list of properties loaded from the CSV file.
     */
    public DetailsButtonHandler(JPanel panel, List<Property> properties) {
        this.panel = panel;
        this.properties = properties;
    }

    /**
     * Action performed when the "Details" button is clicked.
     *
     * @param e The ActionEvent object generated by the button click.
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        String propertyInput = JOptionPane.showInputDialog(panel, "Which property would you like more details on?");
        try {
            int propertyNumber = Integer.parseInt(propertyInput);
            if (propertyNumber > 0 && propertyNumber <= properties.size()) {
                Property property = properties.get(propertyNumber - 1);
                showPropertyDetails(property);
            } else {
                JOptionPane.showMessageDialog(panel, "Property not found.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(panel, "Invalid input. Please enter a valid property number.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Displays the property details in a detailed view.
     *
     * @param property The property to display details for.
     */
    private void showPropertyDetails(Property property) {
        JFrame detailFrame = new JFrame("Property Details");
        detailFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        detailFrame.setSize(800, 600);
        detailFrame.setLayout(new BorderLayout());

        JLabel titleLabel = new JLabel("Property " + property.getObjectId(), SwingConstants.CENTER);
        titleLabel.setFont(new Font("Arial", Font.BOLD, 24));
        detailFrame.add(titleLabel, BorderLayout.NORTH);

        JPanel detailPanel = new JPanel();
        detailPanel.setLayout(new BorderLayout());

        String adjacentProperties = getAdjacentProperties(property);
        String[][] propertyData = {
                {"Object ID", property.getObjectId()},
                {"Parcel ID", property.getParId()},
                {"Parcel Number", property.getParNum()},
                {"Shape Length", property.getShapeLength()},
                {"Shape Area", property.getShapeArea()},
                {"Geometry", property.getGeometry()},
                {"Owner", property.getOwner()},
                {"Freguesia", property.getFreguesia()},
                {"Municipio", property.getMunicipio()},
                {"Ilha", property.getIlha()},
                {"Adjacencies", adjacentProperties}
        };
        String[] columnNames = {"Attribute", "Value"};
        JTable propertyTable = new JTable(propertyData, columnNames);
        JScrollPane tableScrollPane = new JScrollPane(propertyTable);
        detailPanel.add(tableScrollPane, BorderLayout.CENTER);

        JButton backButton = new JButton("Back");
        backButton.setFont(new Font("Arial", Font.BOLD, 16));
        backButton.addActionListener(e -> {
            detailFrame.dispose();
            panel.setVisible(true);
        });

        JPanel buttonPanel = new JPanel();
        buttonPanel.add(backButton);
        detailPanel.add(buttonPanel, BorderLayout.SOUTH);

        detailFrame.add(detailPanel);
        detailFrame.setLocationRelativeTo(null); // Center the frame on screen
        detailFrame.setVisible(true);
    }

    /**
     * Gets the adjacent properties for a given property.
     *
     * @param property The property to find adjacent properties for.
     * @return A string listing the adjacent properties.
     */
    private String getAdjacentProperties(Property property) {
        StringBuilder adjacencyInfo = new StringBuilder();
        for (Property otherProperty : properties) {
            if (!property.equals(otherProperty) && PropertyAdjacencyUtils.areAdjacent(property, otherProperty)) {
                if (adjacencyInfo.length() > 0) {
                    adjacencyInfo.append(", ");
                }
                adjacencyInfo.append(otherProperty.getObjectId());
            }
        }
        return adjacencyInfo.length() > 0 ? adjacencyInfo.toString() : "None";
    }
}
